language: node_js
node_js:
- 10.15.3
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: AJaY7jJWwP7w0Cpq/hivECXE81Bdd5JdQBaDEl2+kNDdkJzxpsp8G7N4rHoEkQU34qUZxqUtDzD/D4j6kuNSCQxgHMSvPaeW+HnZtw3YrI4B96GtajHHJnKaWamTYnyX8Q7L42i04iytiijukX+e1Hf3VIltkUxEzKZc3h5BFmRLfs7lXrN9XnSVkZgG/C/qaV3niS+JhqwZ1VrTgp1F7XE+X0EhnJaPRjz3t18Y661SesKlkZ33Q2dXjXrqaOMIHV4zf26nSs1YYl9N4C5Vp5r2gfH9b3ASCLIRD8F/oOah8IMqhhOcLrzIiZ5XubTIXYjCNS0ywi9x/Vbdhj95jh0r2pvKY17IFR4X8x7+W1mmzgOT7xo8nNF87eXAzVoEpePqzais0MGY93dn0DsyOqzrO1PBwMrU9tbOuWXV6RPCBSlEBkhlodL8x/orFy1uu7khllirFXwJnCCrmvmJXvRWwqOX70EBKM5YPRdRg/sF0Oju5Lo+4q2elzTq5edC7BUC4swavzyG6YM/TzXT9hHuwdqWk/osd7c5kVZBTAVi+Ok0kCCDIa4UrIB85UI5hOKkQIXkhx/OgcyKmhB5XgfKBMclWaAEur7LbtKJaxqMgD5qu08ms/M5uF6nTZBGw9WedfZXfRtS6PgxD7A5DrF28smzoUimSvB0ek9B2uI=
