language: node_js
node_js:
- 10.15.3
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: eErHXaN+phehZ8dmywngYOmloZnrkkPCso/JGe4lCAH8M+BP5RCfV9tg5u/YVkvawtlVylKsPK8UHvPinCcokoHHxlfM4oTasOjCQHlJVWDe5J/WtuJRasP2oGG8LQRZNylyEMZ+qmxMgb6cXwcqqQF72u2DvLN4d5X9X/uCcFejBNl4qJvzU6ceS7ROi7qfKoamP6LbFo5RToB046QqmeoGRTFqvAKc05UwZRpdGPDjO8mLw9QfWoC50Tx2JKUJtB2C4u2PVJrhtPCSt5BFuvuD8BBDfMM9OJH8rpNoCbZ+ZYlD+MLI12UBd9enjTiY99QT56IvScwdNqgQb760Zhv+1kGqQEETtwulM/Cx4DsDsMY07Z3Rzf52pGEFmVB87JW3moovw/rIRXUqO5WWw7aomsl5mtG6VuV1S8O3BvHXx/cIn1TsFrVU+Mf48GlZLMZs+1izkVW/we7feOloxx90LjtjjUEOkdvFi0rxuwwGTUzoJrCfz5qw+1nSCK1VhgB5DHo0K144ZGmHRrf9GnKs7KeQGNm15zauZ585DAprAfdIaXEVlx/6dv2CAqoINCnREB/8TOoTtnTxQO96vZKcMg4BAeZI+xAFnlfmub+vNDaA3xTpL2ufIO549PF7OfucMaZbhN9ROiPpD+878TrjC/9Ng+CtL5Qs8cAOlWQ=

